/**
 * Chain composer tests (task 6.3).
 *
 * Verifies that composeHandler:
 * - produces a complete handler for a linear receive→validate→write-data→respond pipeline
 * - produces a switch statement for a panel with a split rod
 * - deduplicates imports across steps
 * - auto-appends NextResponse.json() when no respond rod present
 */

import { describe, it, expect } from "vitest";
import { composeHandler } from "../adapters/nextjs/chain.js";
import type { Panel, Rod } from "@openstrux/ast";
import type { SplitRoutesExpr } from "@openstrux/ast";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function makePanel(name: string, rods: Rod[]): Panel {
  return {
    kind: "Panel",
    name,
    dp: {},
    access: { kind: "AccessContext" },
    rods,
    snaps: [],
  };
}

function makeReceiveRod(method = "POST"): Rod {
  return {
    kind: "Rod",
    name: "receive",
    rodType: "receive",
    cfg: {
      trigger: {
        kind: "ObjectValue",
        fields: { method: { kind: "LitString", value: method } },
      } as unknown as Rod["cfg"][string],
    },
    arg: {},
  };
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("composeHandler: linear pipeline", () => {
  const rods: Rod[] = [
    makeReceiveRod("POST"),
    {
      kind: "Rod", name: "val", rodType: "validate",
      cfg: { schema: { kind: "TypeRef", name: "Proposal" } as unknown as Rod["cfg"][string] },
      arg: {},
    },
    { kind: "Rod", name: "save", rodType: "write-data", cfg: {}, arg: {} },
  ];
  const panel = makePanel("submit-proposal", rods);
  const file = composeHandler("submit-proposal", rods, panel);

  it("emits to handlers/<panelName>.ts", () => {
    expect(file.path).toBe("handlers/submit-proposal.ts");
  });

  it("contains POST function", () => {
    expect(file.content).toContain("export async function POST");
  });

  it("contains body parsing statement", () => {
    expect(file.content).toContain("await req.json()");
  });

  it("contains Zod parse call", () => {
    expect(file.content).toContain(".parse(body)");
  });

  it("contains prisma create call", () => {
    expect(file.content).toContain(".create({ data: input })");
  });

  it("auto-appends NextResponse.json with status 201 for POST", () => {
    expect(file.content).toContain("NextResponse.json");
    expect(file.content).toContain("status: 201");
  });

  it("NextRequest and NextResponse imports are deduplicated", () => {
    const importLines = file.content.split("\n").filter(l => l.startsWith("import"));
    const nextServerImports = importLines.filter(l => l.includes("next/server"));
    expect(nextServerImports.length).toBe(1);
  });

  it("file starts with generated header", () => {
    expect(file.content.startsWith("// generated by openstrux-generator")).toBe(true);
  });
});

describe("composeHandler: split rod produces switch", () => {
  const routesExpr: SplitRoutesExpr = {
    kind: "SplitRoutesExpr",
    routes: [
      { name: "eligible", predicate: null },
      { name: "ineligible", predicate: null },
      { name: "pending", predicate: null },
    ],
  };
  const rods: Rod[] = [
    makeReceiveRod("GET"),
    {
      kind: "Rod", name: "route", rodType: "split",
      cfg: {},
      arg: { routes: routesExpr as unknown as Rod["arg"][string] },
    },
  ];
  const panel = makePanel("route-panel", rods);
  const file = composeHandler("route-panel", rods, panel);

  it("switch block contains all three cases", () => {
    expect(file.content).toContain('case "eligible":');
    expect(file.content).toContain('case "ineligible":');
    expect(file.content).toContain('case "pending":');
  });
});

describe("composeHandler: explicit respond rod", () => {
  const rods: Rod[] = [
    makeReceiveRod("GET"),
    {
      kind: "Rod", name: "resp", rodType: "respond",
      cfg: { schema: { kind: "TypeRef", name: "Result" } as unknown as Rod["cfg"][string] },
      arg: {},
    },
  ];
  const panel = makePanel("get-result", rods);
  const file = composeHandler("get-result", rods, panel);

  it("contains exactly one NextResponse.json call (from respond rod)", () => {
    const matches = (file.content.match(/NextResponse\.json/g) ?? []).length;
    expect(matches).toBe(1);
  });
});

describe("composeHandler: GET method without respond rod", () => {
  const rods: Rod[] = [makeReceiveRod("GET")];
  const panel = makePanel("health", rods);
  const file = composeHandler("health", rods, panel);

  it("auto-appends status 200 for GET", () => {
    expect(file.content).toContain("status: 200");
  });
});
