/**
 * TypeScript target adapter — implements RFC-0001 for the TypeScript/Prisma/Next.js/Zod target.
 *
 * Spec reference: openstrux-spec/specs/modules/target-ts/generator.md
 *                 openstrux-spec/rfcs/RFC-0001-typescript-target-adapter.md
 */

import type { TypeRecord, TypeEnum, TypeUnion } from "@openstrux/ast";
import type { Panel, Rod } from "@openstrux/ast";
import type { TypeExpr } from "@openstrux/ast";
import type { Adapter, GeneratedFile, GenerateOptions, Manifest, TopLevelNode } from "../../types.js";
import { dispatchRod, isTier2Rod, TIER2_ROD_TYPES } from "./rods/index.js";

// ---------------------------------------------------------------------------
// Prisma accumulator — collects all model/enum blocks into one file
// ---------------------------------------------------------------------------

const FILE_HEADER = "// generated by openstrux-generator — do not edit\n";

const PRISMA_HEADER = `// generated by openstrux-generator — do not edit

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
`;

// ---------------------------------------------------------------------------
// Type-expression mappers
// ---------------------------------------------------------------------------

function tsType(expr: TypeExpr): string {
  switch (expr.kind) {
    case "PrimitiveType": {
      switch (expr.name) {
        case "string": return "string";
        case "number": return "number";
        case "bool":   return "boolean";
        case "date":   return "Date";
        case "bytes":  return "Buffer";
        default:       return expr.name;
      }
    }
    case "ContainerType": {
      const inner = tsType(expr.typeArgs[0] ?? { kind: "PrimitiveType", name: "unknown" } as TypeExpr);
      switch (expr.container) {
        case "Optional": return `${inner} | null`;
        case "Batch":    return `${inner}[]`;
        case "Stream":   return `AsyncIterable<${inner}>`;
        case "Single":   return inner;
        case "Map":      return `Record<string, ${inner}>`;
        default:         return `${expr.container}<${inner}>`;
      }
    }
    case "ConstrainedNumberType": return "number";
    case "ConstrainedStringType": return expr.values.map(v => JSON.stringify(v)).join(" | ");
    case "TypeRef":               return expr.name;
    default:                      return "unknown";
  }
}

function prismaType(expr: TypeExpr, enumNames: Set<string>): string {
  switch (expr.kind) {
    case "PrimitiveType": {
      switch (expr.name) {
        case "string": return "String";
        case "number": return "Float";
        case "bool":   return "Boolean";
        case "date":   return "DateTime";
        case "bytes":  return "Bytes";
        default:       return "String";
      }
    }
    case "ContainerType": {
      const inner = prismaType(expr.typeArgs[0] ?? { kind: "PrimitiveType", name: "string" } as TypeExpr, enumNames);
      switch (expr.container) {
        case "Optional": return `${inner}?`;
        case "Batch":    return `${inner}[]`;
        case "Map":      return "Json";
        default:         return inner;
      }
    }
    case "ConstrainedNumberType": return "Float";
    case "ConstrainedStringType": return "String";
    case "TypeRef":               return expr.name;
    default:                      return "String";
  }
}

function zodType(expr: TypeExpr, enumNames: Set<string>): string {
  switch (expr.kind) {
    case "PrimitiveType": {
      switch (expr.name) {
        case "string": return "z.string()";
        case "number": return "z.number()";
        case "bool":   return "z.boolean()";
        case "date":   return "z.coerce.date()";
        case "bytes":  return "z.instanceof(Buffer)";
        default:       return "z.unknown()";
      }
    }
    case "ContainerType": {
      const inner = zodType(expr.typeArgs[0] ?? { kind: "PrimitiveType", name: "string" } as TypeExpr, enumNames);
      switch (expr.container) {
        case "Optional": return `${inner}.nullable()`;
        case "Batch":    return `${inner}.array()`;
        default:         return inner;
      }
    }
    case "ConstrainedNumberType": return `z.number().min(${expr.min}).max(${expr.max})`;
    case "ConstrainedStringType": return `z.enum([${expr.values.map(v => JSON.stringify(v)).join(", ")}])`;
    case "TypeRef":
      if (enumNames.has(expr.name)) return `z.nativeEnum(${expr.name})`;
      return `z.lazy(() => ${expr.name}Schema)`;
    default: return "z.unknown()";
  }
}

// ---------------------------------------------------------------------------
// Emitters — @type record
// ---------------------------------------------------------------------------

function collectTypeRefs(expr: TypeExpr): string[] {
  if (expr.kind === "TypeRef") return [expr.name];
  if (expr.kind === "ContainerType") return expr.typeArgs.flatMap(collectTypeRefs);
  return [];
}

function emitRecord(
  node: TypeRecord,
  enumNames: Set<string>,
  prismaBlocks: string[]
): GeneratedFile {
  // Collect imports for referenced types (other type files)
  const refNames = new Set<string>();
  for (const f of node.fields) {
    for (const ref of collectTypeRefs(f.type)) {
      if (ref !== node.name) refNames.add(ref);
    }
  }
  const importLines = Array.from(refNames)
    .sort()
    .map(r => `import type { ${r} } from "./${r}.js";`)
    .join("\n");
  const importBlock = importLines ? `\n${importLines}\n` : "";

  // TypeScript interface
  const fields = node.fields
    .map(f => `  ${f.name}: ${tsType(f.type)};`)
    .join("\n");
  const content = `${FILE_HEADER}${importBlock}
export interface ${node.name} {
${fields}
}
`;

  // Prisma model block
  const prismaFields = node.fields.map(f => {
    const pt = prismaType(f.type, enumNames);
    return `  ${f.name.padEnd(16)} ${pt}`;
  }).join("\n");
  prismaBlocks.push(`model ${node.name} {\n${prismaFields}\n}`);

  return { path: `types/${node.name}.ts`, content, lang: "typescript" };
}

// ---------------------------------------------------------------------------
// Emitters — @type enum
// ---------------------------------------------------------------------------

function emitEnum(node: TypeEnum, prismaBlocks: string[]): GeneratedFile {
  const variants = node.variants.map(v => `  ${v} = "${v}",`).join("\n");
  const content = `${FILE_HEADER}
export enum ${node.name} {
${variants}
}
`;
  prismaBlocks.push(`enum ${node.name} {\n${node.variants.map(v => `  ${v}`).join("\n")}\n}`);
  return { path: `types/${node.name}.ts`, content, lang: "typescript" };
}

// ---------------------------------------------------------------------------
// Emitters — @type union
// ---------------------------------------------------------------------------

function emitUnion(node: TypeUnion): GeneratedFile {
  // Collect imports for referenced types
  const refNames = new Set<string>();
  for (const v of node.variants) {
    for (const ref of collectTypeRefs(v.type)) {
      if (ref !== node.name) refNames.add(ref);
    }
  }
  const importLines = Array.from(refNames)
    .sort()
    .map(r => `import type { ${r} } from "./${r}.js";`)
    .join("\n");
  const importBlock = importLines ? `\n${importLines}\n` : "";

  const variants = node.variants
    .map(v => `  | { kind: "${v.tag}"; value: ${tsType(v.type)} }`)
    .join("\n");
  const content = `${FILE_HEADER}${importBlock}
export type ${node.name} =
${variants}
  ;
`;
  return { path: `types/${node.name}.ts`, content, lang: "typescript" };
}

// ---------------------------------------------------------------------------
// Emitters — Zod schema (validate rod)
// ---------------------------------------------------------------------------

function emitZodSchema(
  typeName: string,
  node: TypeRecord,
  enumNames: Set<string>
): GeneratedFile {
  const fields = node.fields
    .map(f => `  ${f.name}: ${zodType(f.type, enumNames)},`)
    .join("\n");
  // Collect enum imports needed
  const enumImports: string[] = [];
  for (const f of node.fields) {
    if (f.type.kind === "TypeRef" && enumNames.has(f.type.name)) {
      enumImports.push(f.type.name);
    }
    if (f.type.kind === "ContainerType" && f.type.typeArgs[0]?.kind === "TypeRef") {
      const ref = f.type.typeArgs[0];
      if (ref.kind === "TypeRef" && enumNames.has(ref.name)) {
        enumImports.push(ref.name);
      }
    }
  }
  const importLines = enumImports.length > 0
    ? enumImports.map(e => `import { ${e} } from "../types/${e}.js";`).join("\n") + "\n"
    : "";
  const content = `${FILE_HEADER}
import { z } from "zod";
${importLines}
export const ${typeName}Schema = z.object({
${fields}
});

export type ${typeName}Input = z.infer<typeof ${typeName}Schema>;
`;
  return { path: `lib/schemas/${typeName}.schema.ts`, content, lang: "typescript" };
}

// ---------------------------------------------------------------------------
// Emitters — route.ts (receive / respond / store / write-data / read-data)
// ---------------------------------------------------------------------------

function httpMethod(rod: Rod): string {
  const trigger = rod.cfg["trigger"];
  if (trigger !== undefined && typeof trigger === "object") {
    const t = trigger as unknown as Record<string, unknown>;
    // Direct method field (NarrowedUnion shorthand)
    const directMethod = t["method"];
    if (typeof directMethod === "string") return directMethod.toUpperCase();
    // Promoted path node: { kind: "TypeRef", config: { method: { kind: "LitString", value: "POST" } } }
    const config = t["config"] as Record<string, unknown> | undefined;
    if (config !== undefined) {
      const methodEntry = config["method"] as Record<string, unknown> | undefined;
      if (methodEntry?.["kind"] === "LitString" && typeof methodEntry["value"] === "string") {
        return (methodEntry["value"] as string).toUpperCase();
      }
    }
    // ObjectValue — look for method field inside fields array
    if (t["kind"] === "ObjectValue" && Array.isArray(t["fields"])) {
      for (const entry of t["fields"] as Array<Record<string, unknown>>) {
        if (entry["key"] === "method" && entry["value"] && typeof entry["value"] === "object") {
          const methodVal = entry["value"] as Record<string, unknown>;
          if (methodVal["kind"] === "LitString" && typeof methodVal["value"] === "string") {
            return (methodVal["value"] as string).toUpperCase();
          }
        }
      }
    }
  }
  return "GET";
}

function emitRouteFile(
  panelName: string,
  rods: Rod[],
  panel: Panel
): GeneratedFile {
  const kebab = panelName;
  const receiveRod = rods.find(r => r.rodType === "receive");
  const respondRod = rods.find(r => r.rodType === "respond");
  const readRods = rods.filter(r => r.rodType === "read-data");

  const method = receiveRod ? httpMethod(receiveRod) : "GET";
  const rodName = receiveRod?.name ?? "handler";

  let lines: string[] = [
    FILE_HEADER,
    `import { NextRequest, NextResponse } from "next/server";`,
    ``,
  ];

  if (respondRod) {
    const schema = respondRod.cfg["schema"] as unknown as Record<string, unknown> | undefined;
    const typeName = schema?.["kind"] === "TypeRef"
      ? String(schema["name"] ?? "unknown")
      : "unknown";
    lines.push(`// Response type: ${typeName} (from respond rod: ${respondRod.name})`);
    lines.push(``);
  }

  for (const rod of readRods) {
    lines.push(`// read-data: ${rod.name}`);
    lines.push(`// TODO: implement read — prisma.<model>.findMany({ where: ... })`);
    lines.push(``);
  }

  // Rod snippets via dispatch table (skips structural rods: receive, respond, guard, validate)
  for (const rod of rods) {
    if (rod.rodType === "read-data") continue; // handled above
    const snippet = dispatchRod(rod, panel);
    if (snippet) {
      lines.push(...snippet.split("\n").map(l => l));
    }
  }

  lines.push(`export async function ${method}(req: NextRequest): Promise<NextResponse> {`);
  lines.push(`  // TODO: implement ${panelName}/${rodName}`);
  lines.push(`  return NextResponse.json({ ok: true });`);
  lines.push(`}`);
  lines.push(``);

  return {
    path: `app/api/${kebab}/route.ts`,
    content: lines.join("\n"),
    lang: "typescript",
  };
}

// ---------------------------------------------------------------------------
// Emitters — guard middleware
// ---------------------------------------------------------------------------

function emitGuardFile(panel: Panel, guardRod: Rod): GeneratedFile {
  const panelName = panel.name;
  const access = panel.access as unknown as Record<string, unknown>;
  const intent = access?.["intent"] as Record<string, unknown> | undefined;
  const purpose = intent ? String(intent["purpose"] ?? "") : "";
  const operation = intent ? String(intent["operation"] ?? "") : "";

  // Derive PascalCase name
  const pascal = panelName
    .split(/[-_]/)
    .map(s => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");

  const content = `${FILE_HEADER}
import { NextRequest, NextResponse } from "next/server";
import type { AccessContext } from "@openstrux/ast";

export interface ${pascal}AccessContext extends AccessContext {
  purpose: "${purpose}";
  operation: "${operation}";
}

export async function withGuard(
  req: NextRequest,
  handler: (req: NextRequest, ctx: ${pascal}AccessContext) => Promise<NextResponse>
): Promise<NextResponse> {
  // TODO: implement access guard for ${panelName}/${guardRod.name}
  const ctx = {} as ${pascal}AccessContext;
  return handler(req, ctx);
}
`;
  return {
    path: `middleware/${panelName}.guard.ts`,
    content,
    lang: "typescript",
  };
}

// ---------------------------------------------------------------------------
// Main adapter implementation
// ---------------------------------------------------------------------------

function generate(
  ast: TopLevelNode[],
  _manifest: Manifest,
  _options: GenerateOptions
): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const prismaBlocks: string[] = [];

  // Build enum name set for TypeRef resolution
  const enumNames = new Set<string>();
  for (const node of ast) {
    if (node.kind === "TypeEnum") enumNames.add(node.name);
  }

  // Build record map for validate rod schema lookup
  const recordMap = new Map<string, TypeRecord>();
  for (const node of ast) {
    if (node.kind === "TypeRecord") recordMap.set(node.name, node);
  }

  // 1. Process all @type nodes
  for (const node of ast) {
    switch (node.kind) {
      case "TypeRecord":
        files.push(emitRecord(node, enumNames, prismaBlocks));
        break;
      case "TypeEnum":
        files.push(emitEnum(node, prismaBlocks));
        break;
      case "TypeUnion":
        files.push(emitUnion(node));
        break;
      default:
        break;
    }
  }

  // 2. Process @panel nodes
  for (const node of ast) {
    if (node.kind !== "Panel") continue;
    const panel = node as Panel;
    const rods = panel.rods as Rod[];

    const hasReceive = rods.some(r => r.rodType === "receive");
    const hasRespond = rods.some(r => r.rodType === "respond");
    const hasStore = rods.some(r => r.rodType === "store");
    const hasWrite = rods.some(r => r.rodType === "write-data");
    const hasRead = rods.some(r => r.rodType === "read-data");
    const guardRod = rods.find(r => r.rodType === "guard");
    const validateRods = rods.filter(r => r.rodType === "validate");

    // Route file (receive + respond + store + write-data + read-data + call + split)
    const hasCall = rods.some(r => r.rodType === "call");
    const hasSplit = rods.some(r => r.rodType === "split");
    if (hasReceive || hasRespond || hasStore || hasWrite || hasRead || hasCall || hasSplit) {
      files.push(emitRouteFile(panel.name, rods, panel));
    }

    // Guard middleware
    if (guardRod !== undefined) {
      files.push(emitGuardFile(panel, guardRod));
    }

    // Zod schemas (validate rods)
    for (const rod of validateRods) {
      const schemaCfg = rod.cfg["schema"];
      let typeName: string | undefined;
      if (schemaCfg !== undefined && typeof schemaCfg === "object") {
        const s = schemaCfg as unknown as Record<string, unknown>;
        if (s["kind"] === "TypeRef") typeName = String(s["name"]);
      }
      if (typeName !== undefined) {
        const record = recordMap.get(typeName);
        if (record !== undefined) {
          files.push(emitZodSchema(typeName, record, enumNames));
        } else {
          // Emit TODO comment stub
          files.push({
            path: `lib/schemas/${typeName}.schema.ts`,
            content: `${FILE_HEADER}\n// TODO: implement expression: schema for ${typeName}\n`,
            lang: "typescript",
          });
        }
      }
    }
  }

  // 3. Emit Prisma schema file (if any models/enums were collected)
  if (prismaBlocks.length > 0) {
    const content = PRISMA_HEADER + "\n" + prismaBlocks.join("\n\n") + "\n";
    files.push({ path: "prisma/schema.prisma", content, lang: "prisma" });
  }

  // 4. Generator summary
  emitGeneratorSummary(ast);

  return files;
}

// ---------------------------------------------------------------------------
// Generator summary — prints rod coverage after generation
// ---------------------------------------------------------------------------

function emitGeneratorSummary(ast: TopLevelNode[]): void {
  let tier1Count = 0;
  let tier2Count = 0;
  const stubPanels: string[] = [];

  for (const node of ast) {
    if (node.kind !== "Panel") continue;
    const panel = node as Panel;
    const rods = panel.rods as Rod[];
    let panelHasStub = false;

    for (const rod of rods) {
      if (isTier2Rod(rod.rodType)) {
        tier2Count++;
        panelHasStub = true;
      } else if (!TIER2_ROD_TYPES.has(rod.rodType)) {
        tier1Count++;
      }
    }

    if (panelHasStub) stubPanels.push(panel.name);
  }

  if (tier1Count === 0 && tier2Count === 0) return;

  console.log(
    `[openstrux-generator] Summary: ${tier1Count} Tier 1 rod(s) emitted, ` +
    `${tier2Count} Tier 2 stub(s) emitted`
  );
  if (stubPanels.length > 0) {
    console.log(
      `[openstrux-generator] Non-demo-capable panels (contain Tier 2 stubs): ${stubPanels.join(", ")}`
    );
  }
}

export const TypeScriptAdapter: Adapter = { generate };
