// generated by openstrux-generator — do not edit

import { NextRequest, NextResponse } from "next/server";

function transformEval(input: Proposal): EligibilityRecord {
  // STRUX-STUB: transform — eval — expression not lowered
  throw new Error("not implemented");
}

export async function GET(req: NextRequest): Promise<NextResponse> {
  const body = await req.json();
  const result = (body as Proposal[]).map((input) => transformEval(input));
  return NextResponse.json(result, { status: 200 });
}
