// generated by openstrux-generator — do not edit

import { NextRequest, NextResponse } from "next/server";

export async function GET(req: NextRequest): Promise<NextResponse> {
  const body = {};
  const result = (body as unknown[]).filter((item) => (item.status === "active") && (item.score > 50));
  return NextResponse.json(result, { status: 200 });
}
