// generated by openstrux-generator — do not edit

import { NextRequest, NextResponse } from "next/server";

export async function GET(req: NextRequest): Promise<NextResponse> {
  const body = {};
  const aggregated = (body as unknown[]).length;
  return NextResponse.json(aggregated, { status: 200 });
}
