// generated by openstrux-generator — do not edit

import { NextRequest, NextResponse } from "next/server";

function guardPolicyExprGuardGolden(ctx: Record<string, unknown>): boolean {
  return ctx.principal.roles.includes("admin");
}

export async function GET(req: NextRequest): Promise<NextResponse> {
  const body = {};
  const _guardCtx = (req as unknown as Record<string, unknown>)["_accessCtx"] as Record<string, unknown> ?? {};
  if (!guardPolicyExprGuardGolden(_guardCtx)) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }
  return NextResponse.json(body, { status: 200 });
}
