/**
 * Shared emitters for TypeScript-targeting adapters: records, enums, unions, Zod schemas.
 *
 * Spec reference: openstrux-spec/specs/modules/target-nextjs/generator.md §4
 */

import type { TypeRecord, TypeEnum, TypeUnion, FieldAnnotation, TypeBlockAnnotation } from "@openstrux/ast";
import type { GeneratedFile } from "../../types.js";
import { tsType, prismaType, zodType, collectTypeRefs } from "./types.js";

const FILE_HEADER = "// generated by openstrux-generator — do not edit\n";

// ---------------------------------------------------------------------------
// Prisma annotation translation helpers
// ---------------------------------------------------------------------------

/** Translate a @pk annotation to Prisma field directives. */
function prismaFromPk(ann: Extract<FieldAnnotation, {kind: "pk"}>, fieldTypePrisma: string): string {
  const gen = ann.default
    ? ann.default
    : fieldTypePrisma === "Int" ? "autoincrement" : "cuid";
  return `@id @default(${gen}())`;
}

/** Translate a @default annotation to Prisma directive. */
function prismaFromDefault(ann: Extract<FieldAnnotation, {kind: "default"}>): string {
  const v = ann.value;
  if (v === "now") return "@default(now())";
  if (typeof v === "boolean") return `@default(${String(v)})`;
  if (typeof v === "number") return `@default(${String(v)})`;
  return `@default(${JSON.stringify(v)})`;
}

/** Translate a @relation annotation to Prisma directive. */
function prismaFromRelation(ann: Extract<FieldAnnotation, {kind: "relation"}>): string {
  const parts = [`fields: [${ann.field}]`, `references: [${ann.ref.field}]`];
  if (ann.onDelete) parts.push(`onDelete: ${ann.onDelete}`);
  if (ann.onUpdate) parts.push(`onUpdate: ${ann.onUpdate}`);
  return `@relation(${parts.join(", ")})`;
}

/** Returns Prisma field-level annotation strings for a field. */
function prismaFieldAnnotations(annotations: readonly FieldAnnotation[], fieldTypePrisma: string): string {
  const parts: string[] = [];
  for (const ann of annotations) {
    switch (ann.kind) {
      case "pk":        parts.push(prismaFromPk(ann, fieldTypePrisma)); break;
      case "default":   parts.push(prismaFromDefault(ann)); break;
      case "unique":    parts.push("@unique"); break;
      case "relation":  parts.push(prismaFromRelation(ann)); break;
      case "updatedAt": parts.push("@updatedAt"); break;
      case "column":    parts.push(`@map("${ann.name}")`); break;
      case "ignore":    parts.push("@ignore"); break;
    }
  }
  return parts.length > 0 ? " " + parts.join(" ") : "";
}

/** Simple heuristic plural for inverse relation field name: lowercase first char + 's'. */
function pluralFieldName(typeName: string): string {
  if (typeName.length === 0) return "items";
  return typeName.charAt(0).toLowerCase() + typeName.slice(1) + "s";
}

// ---------------------------------------------------------------------------
// @type record
// ---------------------------------------------------------------------------

/**
 * Emit a @type record.
 *
 * @param node - The TypeRecord IR node.
 * @param enumNames - Set of enum type names (for Prisma enum refs).
 * @param prismaBlocks - Mutable array; model blocks are pushed here.
 * @param inversions - Mutable map of model → extra inverse fields to append
 *   (populated during processing; used by the caller to apply after all records).
 */
export function emitRecord(
  node: TypeRecord,
  enumNames: Set<string>,
  prismaBlocks: string[],
  inversions: Map<string, string[]>,
): GeneratedFile {
  // @timestamps: inject createdAt and updatedAt into the TS interface
  const extraTsFields: string[] = [];
  const extraPrismaFields: string[] = [];
  if (node.timestamps === true) {
    extraTsFields.push("  createdAt: Date;", "  updatedAt: Date;");
    extraPrismaFields.push(
      `  createdAt        DateTime  @default(now())`,
      `  updatedAt        DateTime  @updatedAt`,
    );
  }

  // --- TypeScript interface ---
  const refNames = new Set<string>();
  for (const f of node.fields) {
    for (const ref of collectTypeRefs(f.type)) {
      if (ref !== node.name) refNames.add(ref);
    }
  }
  const importLines = Array.from(refNames)
    .sort()
    .map(r => `import type { ${r} } from "./${r}.js";`)
    .join("\n");
  const importBlock = importLines ? `\n${importLines}\n` : "";

  const tsFields = node.fields
    .map(f => `  ${f.name}: ${tsType(f.type)};`)
    .join("\n");
  const allTsFields = [tsFields, ...extraTsFields].filter(Boolean).join("\n");
  const content = `${FILE_HEADER}${importBlock}
export interface ${node.name} {
${allTsFields}
}
`;

  // --- Prisma model block ---
  // External types: TS interface is emitted, but NO model block.
  if (node.external !== true) {
    const prismaFieldLines: string[] = [];

    for (const f of node.fields) {
      const annotations = f.annotations ?? [];
      const pt = prismaType(f.type, enumNames);
      const annStr = prismaFieldAnnotations(annotations, pt);
      prismaFieldLines.push(`  ${f.name.padEnd(16)} ${pt}${annStr}`);

      // Track auto-inverse relation: @relation on owned type adds `ownerType[]` to referenced type
      for (const ann of annotations) {
        if (ann.kind === "relation" && ann.ref.model !== "") {
          const invField = `  ${pluralFieldName(node.name).padEnd(16)} ${node.name}[]`;
          if (!inversions.has(ann.ref.model)) inversions.set(ann.ref.model, []);
          inversions.get(ann.ref.model)!.push(invField);
        }
      }
    }

    // Block-level annotations
    const blockLines: string[] = [];
    for (const ba of node.annotations ?? []) {
      blockLines.push(blockAnnotationToPrisma(ba));
    }

    // Timestamps-injected fields
    const allPrismaFields = [...prismaFieldLines, ...extraPrismaFields, ...blockLines];
    prismaBlocks.push(`model ${node.name} {\n${allPrismaFields.join("\n")}\n}`);
  }

  return { path: `types/${node.name}.ts`, content, lang: "typescript" };
}

function blockAnnotationToPrisma(ba: TypeBlockAnnotation): string {
  switch (ba.kind) {
    case "index":  return `  @@index([${ba.fields.join(", ")}])`;
    case "unique": return `  @@unique([${ba.fields.join(", ")}])`;
    case "table":  return `  @@map("${ba.name}")`;
    case "opaque": return `  // @opaque ${ba.content}`;
  }
}

// ---------------------------------------------------------------------------
// @type enum
// ---------------------------------------------------------------------------

export function emitEnum(node: TypeEnum, prismaBlocks: string[]): GeneratedFile {
  const variants = node.variants.map(v => `  ${v} = "${v}",`).join("\n");
  const content = `${FILE_HEADER}
export enum ${node.name} {
${variants}
}
`;
  prismaBlocks.push(`enum ${node.name} {\n${node.variants.map(v => `  ${v}`).join("\n")}\n}`);
  return { path: `types/${node.name}.ts`, content, lang: "typescript" };
}

// ---------------------------------------------------------------------------
// @type union
// ---------------------------------------------------------------------------

export function emitUnion(node: TypeUnion): GeneratedFile {
  const refNames = new Set<string>();
  for (const v of node.variants) {
    for (const ref of collectTypeRefs(v.type)) {
      if (ref !== node.name) refNames.add(ref);
    }
  }
  const importLines = Array.from(refNames)
    .sort()
    .map(r => `import type { ${r} } from "./${r}.js";`)
    .join("\n");
  const importBlock = importLines ? `\n${importLines}\n` : "";

  const variants = node.variants
    .map(v => `  | { kind: "${v.tag}"; value: ${tsType(v.type)} }`)
    .join("\n");
  const content = `${FILE_HEADER}${importBlock}
export type ${node.name} =
${variants}
  ;
`;
  return { path: `types/${node.name}.ts`, content, lang: "typescript" };
}

// ---------------------------------------------------------------------------
// Zod schema (validate rod)
// ---------------------------------------------------------------------------

export function emitZodSchema(
  typeName: string,
  node: TypeRecord,
  enumNames: Set<string>
): GeneratedFile {
  const fields = node.fields
    .map(f => `  ${f.name}: ${zodType(f.type, enumNames)},`)
    .join("\n");

  const enumImports: string[] = [];
  for (const f of node.fields) {
    if (f.type.kind === "TypeRef" && enumNames.has(f.type.name)) {
      enumImports.push(f.type.name);
    }
    if (f.type.kind === "ContainerType" && f.type.typeArgs[0]?.kind === "TypeRef") {
      const ref = f.type.typeArgs[0];
      if (ref.kind === "TypeRef" && enumNames.has(ref.name)) enumImports.push(ref.name);
    }
  }
  const importLines = enumImports.length > 0
    ? enumImports.map(e => `import { ${e} } from "../types/${e}.js";`).join("\n") + "\n"
    : "";

  const content = `${FILE_HEADER}
import { z } from "zod";
${importLines}
export const ${typeName}Schema = z.object({
${fields}
});

export type ${typeName}Input = z.infer<typeof ${typeName}Schema>;
`;
  return { path: `schemas/${typeName}.schema.ts`, content, lang: "typescript" };
}

// ---------------------------------------------------------------------------
// Prisma schema file
// ---------------------------------------------------------------------------

const PRISMA_HEADER = `// generated by openstrux-generator — do not edit

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
`;

export function emitPrismaSchema(prismaBlocks: string[]): GeneratedFile {
  const content = PRISMA_HEADER + "\n" + prismaBlocks.join("\n\n") + "\n";
  // projectRoot: true → the CLI writes this to project root, not .openstrux/build/
  return { path: "prisma/schema.prisma", content, lang: "prisma", projectRoot: true };
}
