/**
 * Shared emitters for TypeScript-targeting adapters: records, enums, unions, Zod schemas.
 *
 * Spec reference: openstrux-spec/specs/modules/target-nextjs/generator.md §4
 */

import type { TypeRecord, TypeEnum, TypeUnion } from "@openstrux/ast";
import type { GeneratedFile } from "../../types.js";
import { tsType, prismaType, zodType, collectTypeRefs } from "./types.js";

const FILE_HEADER = "// generated by openstrux-generator — do not edit\n";

// ---------------------------------------------------------------------------
// @type record
// ---------------------------------------------------------------------------

export function emitRecord(
  node: TypeRecord,
  enumNames: Set<string>,
  prismaBlocks: string[]
): GeneratedFile {
  const refNames = new Set<string>();
  for (const f of node.fields) {
    for (const ref of collectTypeRefs(f.type)) {
      if (ref !== node.name) refNames.add(ref);
    }
  }
  const importLines = Array.from(refNames)
    .sort()
    .map(r => `import type { ${r} } from "./${r}.js";`)
    .join("\n");
  const importBlock = importLines ? `\n${importLines}\n` : "";

  const fields = node.fields
    .map(f => `  ${f.name}: ${tsType(f.type)};`)
    .join("\n");
  const content = `${FILE_HEADER}${importBlock}
export interface ${node.name} {
${fields}
}
`;

  const prismaFields = node.fields.map(f => {
    const pt = prismaType(f.type, enumNames);
    return `  ${f.name.padEnd(16)} ${pt}`;
  }).join("\n");
  prismaBlocks.push(`model ${node.name} {\n${prismaFields}\n}`);

  return { path: `types/${node.name}.ts`, content, lang: "typescript" };
}

// ---------------------------------------------------------------------------
// @type enum
// ---------------------------------------------------------------------------

export function emitEnum(node: TypeEnum, prismaBlocks: string[]): GeneratedFile {
  const variants = node.variants.map(v => `  ${v} = "${v}",`).join("\n");
  const content = `${FILE_HEADER}
export enum ${node.name} {
${variants}
}
`;
  prismaBlocks.push(`enum ${node.name} {\n${node.variants.map(v => `  ${v}`).join("\n")}\n}`);
  return { path: `types/${node.name}.ts`, content, lang: "typescript" };
}

// ---------------------------------------------------------------------------
// @type union
// ---------------------------------------------------------------------------

export function emitUnion(node: TypeUnion): GeneratedFile {
  const refNames = new Set<string>();
  for (const v of node.variants) {
    for (const ref of collectTypeRefs(v.type)) {
      if (ref !== node.name) refNames.add(ref);
    }
  }
  const importLines = Array.from(refNames)
    .sort()
    .map(r => `import type { ${r} } from "./${r}.js";`)
    .join("\n");
  const importBlock = importLines ? `\n${importLines}\n` : "";

  const variants = node.variants
    .map(v => `  | { kind: "${v.tag}"; value: ${tsType(v.type)} }`)
    .join("\n");
  const content = `${FILE_HEADER}${importBlock}
export type ${node.name} =
${variants}
  ;
`;
  return { path: `types/${node.name}.ts`, content, lang: "typescript" };
}

// ---------------------------------------------------------------------------
// Zod schema (validate rod)
// ---------------------------------------------------------------------------

export function emitZodSchema(
  typeName: string,
  node: TypeRecord,
  enumNames: Set<string>
): GeneratedFile {
  const fields = node.fields
    .map(f => `  ${f.name}: ${zodType(f.type, enumNames)},`)
    .join("\n");

  const enumImports: string[] = [];
  for (const f of node.fields) {
    if (f.type.kind === "TypeRef" && enumNames.has(f.type.name)) {
      enumImports.push(f.type.name);
    }
    if (f.type.kind === "ContainerType" && f.type.typeArgs[0]?.kind === "TypeRef") {
      const ref = f.type.typeArgs[0];
      if (ref.kind === "TypeRef" && enumNames.has(ref.name)) enumImports.push(ref.name);
    }
  }
  const importLines = enumImports.length > 0
    ? enumImports.map(e => `import { ${e} } from "../types/${e}.js";`).join("\n") + "\n"
    : "";

  const content = `${FILE_HEADER}
import { z } from "zod";
${importLines}
export const ${typeName}Schema = z.object({
${fields}
});

export type ${typeName}Input = z.infer<typeof ${typeName}Schema>;
`;
  return { path: `schemas/${typeName}.schema.ts`, content, lang: "typescript" };
}

// ---------------------------------------------------------------------------
// Prisma schema file
// ---------------------------------------------------------------------------

const PRISMA_HEADER = `// generated by openstrux-generator — do not edit

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
`;

export function emitPrismaSchema(prismaBlocks: string[]): GeneratedFile {
  const content = PRISMA_HEADER + "\n" + prismaBlocks.join("\n\n") + "\n";
  return { path: "prisma/schema.prisma", content, lang: "prisma" };
}
